# Fictitious Names

In [49]:
# import numpy as np
import pandas as pd

### Step 2. Create the 3 DataFrames based on the following raw data

In [50]:
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

### Step 3. Assign each to a variable called data1, data2, data3

In [51]:
data1 = pd.DataFrame(raw_data_1)
data2 = pd.DataFrame(raw_data_2)
data3 = pd.DataFrame(raw_data_3)
data1

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [52]:
data2

  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [53]:
data3

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

### Step 4. Join the two first dataframes along rows and assign to all_data

In [54]:
all_data = pd.concat([data1, data2], axis=0, ignore_index=True)
all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
5          4      Billy    Bonder
6          5      Brian     Black
7          6       Bran   Balwner
8          7      Bryce     Brice
9          8      Betty    Btisan

### Step 5. Join the two first dataframes along columns and assing to all_data_col

In [55]:
all_data_col = data1.merge(data2, on="subject_id")
all_data_col

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Step 6. Print the unique values of data3

In [56]:
data3.drop_duplicates(subset="test_id").sort_values("test_id")

  subject_id  test_id
7          9        1
5          7       14
1          2       15
4          5       16
0          1       51
3          4       61

### Step 7. Merge all_data and data3 along the subject_id value

In [57]:
all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
5          4      Billy    Bonder
6          5      Brian     Black
7          6       Bran   Balwner
8          7      Bryce     Brice
9          8      Betty    Btisan

In [58]:
data3

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

In [59]:
merged_data = all_data.merge(data3, on="subject_id", how="outer")
merged_data

   subject_id first_name last_name  test_id
0           1       Alex  Anderson     51.0
1          10        NaN       NaN     61.0
2          11        NaN       NaN     16.0
3           2        Amy  Ackerman     15.0
4           3      Allen       Ali     15.0
5           4      Alice      Aoni     61.0
6           4      Billy    Bonder     61.0
7           5     Ayoung   Atiches     16.0
8           5      Brian     Black     16.0
9           6       Bran   Balwner      NaN
10          7      Bryce     Brice     14.0
11          8      Betty    Btisan     15.0
12          9        NaN       NaN      1.0

### Step 8. Merge only the data that has the same 'subject_id' on both data1 and data2

In [60]:
data1

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [61]:
data2

  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [66]:
merged_data2 = data1.merge(data2, on="subject_id", how="inner")
merged_data2

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Step 9. Merge all values in data1 and data2, with matching records and not matching records from both sides where available.

In [67]:
merged_data3 = data1.merge(data2, on="subject_id", how="outer") #outer conserva todos los subject_id de ambos DataFrames
merged_data3

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan