   #                                                  Titanic Exercise 

   ![titanic](https://userscontent2.emaze.com/images/a5f68f37-6349-4065-a1fc-921cbe7401b2/958230111417e36d6b3c67ffd7bc3494.jpeg)
   #### Practise Pandas

First of all, import the needed libraries.

In [162]:
import pandas as pd
import numpy as np

1. Read in filename and call the variable `titanic`
    - Explore the `titanic` dataset using `info`, `dtypes` & `describe`

In [163]:
titanic = pd.read_csv("./data/titanic.csv")

titanic.head(50)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.00,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
10,1,0,"Astor, Col. John Jacob",male,47.00,1,0,PC 17757,227.5250,C62 C64,C,NaN,124.0,"New York, NY"
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C,4,NaN,"New York, NY"
12,1,1,"Aubart, Mme. Leontine Pauline",female,24.00,0,0,PC 17477,69.3000,B35,C,9,NaN,"Paris, France"
13,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.00,0,0,19877,78.8500,NaN,S,6,NaN,NaN
14,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
15,1,0,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,NaN,NaN,"New York, NY"
16,1,0,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C,NaN,NaN,"Montreal, PQ"
17,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C,6,NaN,"Montreal, PQ"
18,1,1,"Bazzani, Miss. Albina",female,32.00,0,0,11813,76.2917,D15,C,8,NaN,NaN
19,1,0,"Beattie, Mr. Thomson",male,36.00,0,0,13050,75.2417,C6,C,A,NaN,"Winnipeg, MN"
20,1,1,"Beckwith, Mr. Richard Leonard",male,37.00,1,1,11751,52.5542,D35,S,5,NaN,"New York, NY"
21,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.00,1,1,11751,52.5542,D35,S,5,NaN,"New York, NY"
22,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.0000,C148,C,5,NaN,"New York, NY"
23,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C,4,NaN,NaN
24,1,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.7792,C97,S,8,NaN,NaN
25,1,0,"Birnbaum, Mr. Jakob",male,25.00,0,0,13905,26.0000,NaN,C,NaN,148.0,"San Francisco, CA"
26,1,1,"Bishop, Mr. Dickinson H",male,25.00,1,0,11967,91.0792,B49,C,7,NaN,"Dowagiac, MI"
27,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.00,1,0,11967,91.0792,B49,C,7,NaN,"Dowagiac, MI"
28,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S,8,NaN,NaN
29,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.00,0,0,110564,26.5500,C52,S,D,NaN,"Stockholm, Sweden / Washington, DC"
30,1,0,"Blackwell, Mr. Stephen Weart",male,45.00,0,0,113784,35.5000,T,S,NaN,NaN,"Trenton, NJ"
31,1,1,"Blank, Mr. Henry",male,40.00,0,0,112277,31.0000,A31,C,7,NaN,"Glen Ridge, NJ"
32,1,1,"Bonnell, Miss. Caroline",female,30.00,0,0,36928,164.8667,C7,S,8,NaN,"Youngstown, OH"
33,1,1,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,26.5500,C103,S,8,NaN,"Birkdale, England Cleveland, Ohio"
34,1,0,"Borebank, Mr. John James",male,42.00,0,0,110489,26.5500,D22,S,NaN,NaN,"London / Winnipeg, MB"
35,1,1,"Bowen, Miss. Grace Scott",female,45.00,0,0,PC 17608,262.3750,NaN,C,4,NaN,"Cooperstown, NY"
36,1,1,"Bowerman, Miss. Elsie Edith",female,22.00,0,1,113505,55.0000,E33,S,6,NaN,"St Leonards-on-Sea, England Ohio"
37,1,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,9,NaN,"Los Angeles, CA"
38,1,0,"Brady, Mr. John Bertram",male,41.00,0,0,113054,30.5000,A21,S,NaN,NaN,"Pomeroy, WA"
39,1,0,"Brandeis, Mr. Emil",male,48.00,0,0,PC 17591,50.4958,B10,C,NaN,208.0,"Omaha, NE"
40,1,0,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,NaN,NaN,"Philadelphia, PA"
41,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.00,0,0,PC 17610,27.7208,B4,C,6,NaN,"Denver, CO"
42,1,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.00,2,0,11769,51.4792,C101,S,D,NaN,"Belmont, MA"
43,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00,0,0,11813,76.2917,D15,C,8,NaN,"Philadelphia, PA"
44,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C,3,NaN,NaN
45,1,0,"Butt, Major. Archibald Willingham",male,45.00,0,0,113050,26.5500,B38,S,NaN,NaN,"Washington, DC"
46,1,0,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,NaN,NaN,NaN
47,1,1,"Calderhead, Mr. Edward Pennington",male,42.00,0,0,PC 17476,26.2875,E24,S,5,NaN,"New York, NY"
48,1,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.00,0,0,PC 17606,27.4458,NaN,C,6,NaN,"Washington, DC"
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Austria-Hungary / Germantown, Philadelphia, PA"

In [164]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: float64(3), int64(4), str(7)
memory usage: 143.3 KB

In [165]:
titanic.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881138,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413493,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.170000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

2. Create a separate dataframe with the columns `['name', 'sex', 'age']`, call it `people`

It can be done two ways, do it both!

In [166]:
people = titanic[["name","sex","age"]]
people

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

In [167]:
people_1 = titanic.loc[:, ["name","sex","age"]]
people_1

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

3. Print the output of `people` showing the first three rows and the last four rows, using `append`,`tail` and `head`

In [168]:
pd.concat([people.head(3), people.tail(4)])

                                name     sex    age
0      Allen, Miss. Elisabeth Walton  female  29.00
1     Allison, Master. Hudson Trevor    male   0.92
2       Allison, Miss. Helen Loraine  female   2.00
1305           Zabour, Miss. Thamine  female    NaN
1306       Zakarian, Mr. Mapriededer    male  26.50
1307             Zakarian, Mr. Ortin    male  27.00
1308              Zimmerman, Mr. Leo    male  29.00

4. Slice the row from 3 to 9, call it `s_titanic`

In [169]:
s_titanic = titanic.loc[3:9]
s_titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

5. Slice the row from 40 to 63 in reverse order, call it `s_titanic_rev`

In [170]:
s_titanic_rev = titanic[63:40:-1]
s_titanic_rev

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
63,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,4,NaN,"Amenia, ND"
62,1,0,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S,NaN,NaN,"Amenia, ND"
61,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
60,1,0,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.8500,C46,S,NaN,172.0,"Little Onn Hall, Staffs"
59,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,5,NaN,"New York, NY"
58,1,0,"Case, Mr. Howard Brown",male,49.0,0,0,19924,26.0000,NaN,S,NaN,NaN,"Ascot, Berkshire / Rochester, NY"
57,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
56,1,1,"Carter, Mr. William Ernest",male,36.0,1,2,113760,120.0000,B96 B98,S,C,NaN,"Bryn Mawr, PA"
55,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
54,1,1,"Carter, Master. William Thornton II",male,11.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
53,1,0,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
52,1,0,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
51,1,0,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,NaN,NaN,"New York, NY"
50,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Germantown, Philadelphia, PA"
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Austria-Hungary / Germantown, Philadelphia, PA"
48,1,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0,0,0,PC 17606,27.4458,NaN,C,6,NaN,"Washington, DC"
47,1,1,"Calderhead, Mr. Edward Pennington",male,42.0,0,0,PC 17476,26.2875,E24,S,5,NaN,"New York, NY"
46,1,0,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,NaN,NaN,NaN
45,1,0,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S,NaN,NaN,"Washington, DC"
44,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C,3,NaN,NaN
43,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0,0,0,11813,76.2917,D15,C,8,NaN,"Philadelphia, PA"
42,1,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S,D,NaN,"Belmont, MA"
41,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C,6,NaN,"Denver, CO"

6. Slice the columns from the starting column to `'parch'`, call it `left_columns`

In [171]:
left_colums = titanic.loc[:, :"parch"]
left_colums

,pclass,survived,name,sex,age,sibsp,parch
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2
...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0

7. Slice the columns from `'name'` to `'age'`, call it `middle_columns`

In [172]:
middle_columns = titanic.loc[:,"name":"age"]
middle_columns

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

8. Slice the columns from `'ticket'` to the end, call it `right_columns`

In [173]:
right_columms = titanic.loc[:, :"ticket":]
right_columms

,pclass,survived,name,sex,age,sibsp,parch,ticket
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781
...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082

9. What is the name of the oldest person who died in the Titanic? Was he or she travelling alone or had any family travelling with them?

In order to give an answer to the second question you should find out which columns give you that info. Usually part of your job as a Data Scientist will be get to know the dataset which you are working with. In this case the columns which give you that info are the following: 
        - 'sibsp' Number of Siblings/Spouses Aboard
        - 'parch' Number of Parents/Children Aboard

In [174]:
died = titanic.loc[(titanic["survived"] == 0) & titanic["age"].notna()]

oldest_person = died.loc[died["age"].idxmax(), ["name", "age", "sibsp", "parch"]]

oldest_person

name     Svensson, Mr. Johan
age                     74.0
sibsp                      0
parch                      0
Name: 1235, dtype: object

10. Create the list of 5 random numbers of rows from 0 to the lenght of the dataframe, call it `rows`

ex. `rows = [3,7,99,52,48]` use `random` library

This list of numbers are random, could be different.

In [175]:
import random

In [176]:
rows = random.sample(range(len(titanic)-1), 5)
rows

[815, 590, 756, 523, 224]

11. Create the list of three column labels, call it `cols`

In [177]:
cols = random.sample(list(titanic.columns),3)
cols

['boat', 'ticket', 'embarked']

12. Use both lists `rows` and `cols` to create a new dataframe

In [178]:
df_new = titanic.loc[rows,cols]
df_new

    boat       ticket embarked
815  NaN       358585        S
590   10   C.A. 34651        S
756  NaN       386525        S
523   13  W./C. 14260        S
224  NaN       113043        S

13. Create a boolean array with the condition of being a woman or a man, using the `sex` column, where **female** is True. Call it `array_fe`

In [179]:
array_fe = titanic["sex"] == "female"
array_fe

0        True
1       False
2        True
3       False
4        True
        ...
1304     True
1305     True
1306    False
1307    False
1308    False
Name: sex, Length: 1309, dtype: bool

14. Rename the column `"sex"` to `"gender"` and filter the `titanic` dataframe with the boolean array, call it `woman_titanic`

In [180]:
titanic = titanic.rename(columns={"sex": "gender"})

woman_titanic = titanic.loc[array_fe]

woman_titanic

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1286,3,1,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,C,NaN,NaN
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,NaN,NaN,NaN
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN

15. How many woman were younger than 18? Call the variable `minor_wo`

In [181]:
minor_wo = woman_titanic.loc[woman_titanic["age"] < 18].shape[0]
minor_wo

72

16. How many woman that were less than 18 actually died? Call the variable `dead_wo`

In [182]:
dead_wo = woman_titanic.loc[(woman_titanic["age"] < 18) & (woman_titanic["survived"] == 0)
].shape[0]

dead_wo

22

17. Drop rows with *Nan* in `titanic` with `how='any'` and print the shape

In [196]:
titanic.dropna(how="any", inplace=False)
print(titanic.shape)

(1309, 14)

18. Drop rows with *Nan* in `titanic` with `how='all'` and print the shape

In [197]:
titanic.dropna(how="all",inplace=False)
print(titanic.shape)

(1309, 14)

Check in [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) why the shapes are different.

In [195]:
titanic[titanic["name"].str.contains("Smith, ", case=False)]

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
267,1,0,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C,NaN,NaN,"St James, Long Island, NY"
268,1,0,"Smith, Mr. Lucien Philip",male,24.0,1,0,13695,60.0000,C31,S,NaN,NaN,"Huntington, WV"
269,1,0,"Smith, Mr. Richard William",male,NaN,0,0,113056,26.0000,A19,S,NaN,NaN,"Streatham, Surrey"
270,1,1,"Smith, Mrs. Lucien Philip (Mary Eloise Hughes)",female,18.0,1,0,13695,60.0000,C31,S,6,NaN,"Huntington, WV"
564,2,1,"Smith, Miss. Marion Elsie",female,40.0,0,0,31418,13.0000,NaN,S,9,NaN,NaN
820,3,1,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,NaN,S,C D,NaN,"Strood, Kent, England Detroit, MI"
821,3,0,"Goldsmith, Mr. Frank John",male,33.0,1,1,363291,20.5250,NaN,S,NaN,NaN,"Strood, Kent, England Detroit, MI"
822,3,0,"Goldsmith, Mr. Nathan",male,41.0,0,0,SOTON/O.Q. 3101263,7.8500,NaN,S,NaN,NaN,"Philadelphia, PA"
823,3,1,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.5250,NaN,S,C D,NaN,"Strood, Kent, England Detroit, MI"
1215,3,0,"Smith, Mr. Thomas",male,NaN,0,0,384461,7.7500,NaN,Q,NaN,NaN,NaN

19. Drop columns in `titanic` with more than 1000 missing values and print the columns remaining

In [198]:
columns_drop = titanic.columns[titanic.isna().sum() > 1000]
titanic.drop(columns=columns_drop, inplace=True)

print(titanic.columns)
titanic

Index(['pclass', 'survived', 'name', 'gender', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'embarked', 'boat', 'home.dest'],
      dtype='str')

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,embarked,boat,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,S,2,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,11,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,C,NaN,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,C,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,C,NaN,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,C,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,S,NaN,NaN

20. Calculate the ratio of missing values at the `boat` column.

In [200]:
ratio_perdida_valores = titanic["boat"].isna().mean()
print(ratio_perdida_valores)
print(f"{ratio_perdida_valores:.2%}")

0.6287242169595111
62.87%

21.  Group `titanic` by `'pclass'` and aggregate by the columns `age` & `fare`, by `max` and `median` and assign it to `by_class`

In [201]:
by_class = titanic.groupby("pclass")[["age", "fare"]].agg(["max", "median"])
by_class

         age             fare
         max median       max   median
pclass
1       80.0   39.0  512.3292  60.0000
2       70.0   29.0   73.5000  15.0458
3       74.0   24.0   69.5500   8.0500

22. Print the maximum age in each class from `by_class`

In [206]:
print(by_class["age"]["max"])

pclass
1    80.0
2    70.0
3    74.0
Name: max, dtype: float64

23. Print the median fare in each class from `by_class`

In [207]:
print(by_class["fare"]["median"])

pclass
1    60.0000
2    15.0458
3     8.0500
Name: median, dtype: float64

24. Using [`.pivot_table()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) to count how many women or men survived by class, call it `counted`.

Don't panic and read the documentation!

In [209]:
counted = titanic.pivot_table(
    index="pclass",
    columns="gender",
    values="survived",
    aggfunc="sum"
)
counted

gender  female  male
pclass
1          139    61
2           94    25
3          106    75

25. Add a new column with the sum of survived men and women, call it `counted['total']`

In [210]:
counted["total"] = counted.sum(axis=1)
counted

gender  female  male  total
pclass
1          139    61    200
2           94    25    119
3          106    75    181

26. Sort `counted` by the `'total'` column. In which class the people survived the most?

27. Please, show only the rows using a mask with the following conditions: 
    - They are woman
    - From third class
    - Younger than 30
    - They survived
    
    ¿How many rows fulfill the condition?

28. Now, show only the rows using `.loc` with the following conditions: 
    - They are man
    - From first class
    - Older than 50
    - They died
    
    ¿How many rows fulfill the condition?

29. Print the uniques values at the column `'name'`

In [186]:
titanic['name'].nunique()

1307

30. Find if was there any `name` repeated at the Titanic?

Hint: There were two people with the same name, who?

31. Using `matplotlib` find the appropriate visualization to show the distribution of the column `'age'`

In [187]:
import matplotlib.pyplot as plt

32. Using `matplotlib` find the appropriate plot to visualize the column `'gender'`

32b. What if you also plot the column `'gender'` using the function [`countplot`](https://seaborn.pydata.org/generated/seaborn.countplot.html) from the library [`seaborn`](https://seaborn.pydata.org/)?

Remember you have never used `seaborn` before, therefore you should install it before importing it.

In [188]:
import seaborn as sns

33. Using the function [`catplot`](https://seaborn.pydata.org/generated/seaborn.catplot.html) from the library `seaborn`, find out if the hypothesis _"Women are more likely to survive shipwrecks"_ is true or not.

You should get something like this:

![catplot](./img/catplotgen.png)

34. Using [`kdeplot`]("https://seaborn.pydata.org/generated/seaborn.kdeplot.html") from `seaborn` represent those who not survived distributed by age.<>

Hint: First you should "filter" the `titanic` dataset where the column "survived" is 0, indexing the column `"age"` only.

Arguments you should pass to the function: 

    - color = "red"
    - label = "Not Survived"
    - shade = True
    
You should get something like this:

![kdeplot](./img/kdeplotsur.png)