# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [47]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [48]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [49]:
chipo["item_price"] = pd.to_numeric(
    chipo["item_price"].astype(str).str.replace("$", "", regex=False),
    errors="coerce"
)

In [50]:
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]  # precio unitario

In [51]:
# item_price is already numeric from the earlier cell
chipo["item_price"] = pd.to_numeric(chipo["item_price"], errors="coerce")
chipo.nlargest(1, "item_price")["item_name"]

chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
 5   unit_price          4622 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 216.8 KB

### Step 4. How many products cost more than $10.00?

In [52]:
chipo[chipo["unit_price"] > 10.00][["item_name", "item_price"]]

               item_name  item_price
5           Chicken Bowl       10.98
7          Steak Burrito       11.75
13          Chicken Bowl       11.25
23       Chicken Burrito       10.98
39         Barbacoa Bowl       11.75
...                  ...         ...
4610       Steak Burrito       11.75
4611      Veggie Burrito       11.25
4617       Steak Burrito       11.75
4618       Steak Burrito       11.75
4619  Chicken Salad Bowl       11.25

[1034 rows x 2 columns]

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [53]:
chipo[chipo["unit_price"] > 10]["order_id"].nunique()

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [54]:
print((chipo["item_price"]>10).sum())
#conteo de pedidos diferntes
print(chipo.loc[chipo["item_price"]>10, "order_id"].nunique())

1130
863

In [55]:
precio_order = chipo[["item_price", "order_id"]]
print(precio_order)

      item_price  order_id
0           2.39         1
1           3.39         1
2           3.39         1
3           2.39         1
4          16.98         2
...          ...       ...
4617       11.75      1833
4618       11.75      1833
4619       11.25      1834
4620        8.75      1834
4621        8.75      1834

[4622 rows x 2 columns]

In [56]:
total_por_pedido = precio_order.groupby(chipo["order_id"])["item_price"].sum()#groupby para agrupar filas x num de pedidos.

(total_por_pedido)

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: item_price, Length: 1834, dtype: float64

In [57]:
print((precio_order.groupby(chipo["order_id"]).sum() > 10). sum())

item_price    1834
dtype: int64

In [58]:
totales_por_pedido = chipo.groupby(["order_id"])['item_price'].sum() #uso groupby para agrupar filas x num de pedido
print(len(totales_por_pedido[totales_por_pedido>10])) #BIEN!!!!!! :slightly_smiling_face:

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [59]:
print(chipo.loc[(chipo['item_price']>10) & (chipo['quantity']>1), 'order_id'].nunique())

117

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [60]:
#chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]
chipo[["item_name", "unit_price"]]

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [65]:
chipo_ordenado = chipo.sort_values(by="item_name")
chipo_ordenado

,order_id,quantity,item_name,choice_description,item_price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

In [66]:

chipo[["item_name", "unit_price"]].sort_values("item_name")

              item_name  unit_price
3389  6 Pack Soft Drink        6.49
341   6 Pack Soft Drink        6.49
1849  6 Pack Soft Drink        6.49
1860  6 Pack Soft Drink        6.49
2713  6 Pack Soft Drink        6.49
...                 ...         ...
2384  Veggie Soft Tacos        8.75
781   Veggie Soft Tacos        8.75
2851  Veggie Soft Tacos        8.49
1699  Veggie Soft Tacos       11.25
1395  Veggie Soft Tacos        8.49

[4622 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [18]:
print(chipo.nlargest(1, "item_price")["quantity"])

print("___________________________________")

chipo[chipo["item_price"] == chipo["item_price"].max()]["quantity"]

3598    15
Name: quantity, dtype: int64
___________________________________

3598    15
Name: quantity, dtype: int64

In [ ]:
#LARA EXAMPLE
idx_implicito = chipo_ordenado['item_price'].argmax()
idx_explicito = chipo_ordenado['item_price'].idxmax()
#usamos chipo_ordenado para ver lo de los ínidces implícitos y explícitos
#chipo['item_price'].idxmax() devuelve el índice explícito
#en chipo y chipo_ordenado los índices explícitos sí hacen referencia al mismo producto
print(chipo_ordenado.loc[idx_explicito, 'quantity'])
#iloc devuelve el índice implícito
print(chipo_ordenado.iloc[idx_implicito]['quantity'])

print(chipo.iloc[chipo['item_price'].argmax()]['quantity'])

print(chipo_ordenado.loc[idx_explicito])
print(chipo_ordenado.iloc[idx_implicito])

15
15
15
order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
unit_price                                    2.95
Name: 3598, dtype: object
order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
unit_price                                    2.95
Name: 3598, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [69]:
(chipo["item_name"] == "Veggie Salad Bowl").sum()

#chipo.loc[chipo(["item_name"] == "Veggie Salad Bowl", "quiantity").sum()]

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [ ]:
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]

20